from __future__ import annotations

from datetime import datetime
from pathlib import Path
import argparse
import re
import sqlite3
import traceback
from typing import Any

import geopandas as gpd
import pandas as pd
import yaml


# =============================================================================
# Module 06 - Prepare Sentinel-2 SR GEE input points
# =============================================================================
# This script prepares eligible point records for Sentinel-2 Surface Reflectance
# extraction in Google Earth Engine.
#
# Expected project structure:
#
# PGBM_actividad_1_diagnostico/
# ├─ config/config.yaml
# ├─ data/interim/03b_multirregistros_xy.sqlite
# ├─ data/processed/
# ├─ outputs/
# ├─ logs/
# └─ src/06_s2_sr_gee_input.py
#
# Run from the project root:
#
# python src/06_s2_sr_gee_input.py
#
# Optional:
#
# python src/06_s2_sr_gee_input.py --skip-gpkg
# python src/06_s2_sr_gee_input.py --batch-size 50000
# =============================================================================


YEAR_MIN = 2018
YEAR_MAX = 2022

DEFAULT_BATCH_SIZE = 50000
COORD_DECIMALS = 10


def find_project_root() -> Path:
    """
    Find project root by searching upward for config/config.yaml.

    This makes the script robust when executed from bash, VS Code, or another
    working directory, as long as the file is inside the repository.
    """
    candidates = []

    try:
        candidates.append(Path(__file__).resolve().parent)
    except NameError:
        pass

    candidates.append(Path.cwd().resolve())

    visited: set[Path] = set()

    for start in candidates:
        for path in [start, *start.parents]:
            if path in visited:
                continue
            visited.add(path)

            if (path / "config" / "config.yaml").exists():
                return path

    raise FileNotFoundError(
        "No se pudo localizar la raíz del proyecto. "
        "El script debe estar dentro del repositorio y debe existir config/config.yaml."
    )


PROJECT_ROOT = find_project_root()

CONFIG_PATH = PROJECT_ROOT / "config" / "config.yaml"
INTERIM_DB_PATH = PROJECT_ROOT / "data" / "interim" / "03b_multirregistros_xy.sqlite"

OUTPUT_DIR = PROJECT_ROOT / "data" / "processed" / "s2_sr_gee_input"
BATCHES_DIR = OUTPUT_DIR / "batches"

TABLES_DIR = PROJECT_ROOT / "outputs" / "tables" / "s2_sr_gee_input"
REPORTS_DIR = PROJECT_ROOT / "outputs" / "reports" / "s2_sr_gee_input"
LOGS_DIR = PROJECT_ROOT / "logs"

OUTPUT_GPKG = OUTPUT_DIR / "puntos_s2_sr_2018_2022.gpkg"
OUTPUT_LAYER = "puntos_s2_sr_2018_2022"

EXTRACT_UNITS_CSV = OUTPUT_DIR / "s2_sr_extract_units_2018_2022.csv"


def crear_carpetas_salida() -> None:
    """Create all output folders required by this module."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    BATCHES_DIR.mkdir(parents=True, exist_ok=True)
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)


def registrar_log(mensaje: str) -> None:
    """Append a message to the audit log."""
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_path = LOGS_DIR / "auditoria.log"

    with open(log_path, "a", encoding="utf-8") as log:
        log.write(f"[{fecha}] {mensaje}\n")


def cargar_yaml(path: Path) -> dict[str, Any]:
    """Load YAML file."""
    if not path.exists():
        raise FileNotFoundError(f"No existe el archivo requerido: {path}")

    with open(path, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    if data is None:
        return {}

    if not isinstance(data, dict):
        raise ValueError(f"El archivo YAML no contiene un diccionario válido: {path}")

    return data


def resolver_ruta_proyecto(path_value: str | Path) -> Path:
    """
    Resolve a path from config.

    If the path is absolute, keep it.
    If it is relative, resolve it from PROJECT_ROOT.
    """
    path = Path(path_value)

    if path.is_absolute():
        return path

    return PROJECT_ROOT / path


def abrir_conexion_intermedia() -> sqlite3.Connection:
    """Open SQLite database generated by Module 3B."""
    if not INTERIM_DB_PATH.exists():
        raise FileNotFoundError(
            f"No existe la base intermedia: {INTERIM_DB_PATH}. "
            "Ejecute primero el Módulo 3B para generar la tabla grupos_xy."
        )

    conn = sqlite3.connect(INTERIM_DB_PATH)
    conn.execute("PRAGMA temp_store = MEMORY;")
    conn.execute("PRAGMA cache_size = -200000;")
    return conn


def tabla_existe(conn: sqlite3.Connection, table_name: str) -> bool:
    """Check if a SQLite table exists."""
    sql = """
    SELECT COUNT(*) AS n
    FROM sqlite_master
    WHERE type = 'table' AND name = ?;
    """
    n = conn.execute(sql, (table_name,)).fetchone()[0]
    return int(n) > 0


def normalizar_coord(series: pd.Series) -> pd.Series:
    """
    Convert coordinates to numeric values and round them consistently.

    This reduces failed joins caused by tiny floating point representation
    differences between the source GeoPackage and the intermediate SQLite DB.
    """
    return pd.to_numeric(series, errors="coerce").round(COORD_DECIMALS)


def cargar_grupos_xy() -> pd.DataFrame:
    """Load XY groups from the intermediate SQLite database."""
    conn = abrir_conexion_intermedia()

    try:
        if not tabla_existe(conn, "grupos_xy"):
            raise ValueError(
                "No existe la tabla grupos_xy en la base intermedia. "
                "Ejecute primero el Módulo 3B."
            )

        sql = """
        SELECT
            xy_group_id,
            lon,
            lat,
            n_registros,
            n_paises,
            n_fuentes,
            n_anios,
            n_nivel1,
            n_nivel2,
            anio_min,
            anio_max,
            pais_grupo,
            conf_integrada_promedio,
            conf_integrada_min,
            conf_integrada_max,
            tipo_grupo_xy
        FROM grupos_xy;
        """

        grupos_xy = pd.read_sql_query(sql, conn)

    finally:
        conn.close()

    required = {"lon", "lat"}
    missing = required.difference(grupos_xy.columns)
    if missing:
        raise ValueError(
            "La tabla grupos_xy no contiene los campos requeridos: "
            f"{sorted(missing)}"
        )

    grupos_xy["_lon_join"] = normalizar_coord(grupos_xy["lon"])
    grupos_xy["_lat_join"] = normalizar_coord(grupos_xy["lat"])

    grupos_xy = grupos_xy.drop(columns=["lon", "lat"])

    duplicated = grupos_xy.duplicated(subset=["_lon_join", "_lat_join"]).sum()
    if duplicated:
        print(
            "Advertencia: grupos_xy contiene coordenadas duplicadas después de "
            f"normalizar lon/lat: {duplicated:,} duplicados."
        )

    return grupos_xy


def limpiar_nombre_archivo(value: object) -> str:
    """Create a safe text fragment for filenames."""
    if pd.isna(value):
        return "NA"

    text = str(value)
    text = text.strip()
    text = text.replace(" ", "_")
    text = re.sub(r"[^A-Za-z0-9_\-]+", "", text)
    text = re.sub(r"_+", "_", text)

    if not text:
        return "NA"

    return text[:80]


def exportar_tabla_conteo(
    df: pd.DataFrame,
    field: str | None,
    output_csv: Path,
) -> None:
    """Export a frequency table for a field."""
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    if not field or field not in df.columns:
        pd.DataFrame(
            [{"warning": f"Campo no encontrado o no configurado: {field}"}]
        ).to_csv(output_csv, index=False, encoding="utf-8-sig")
        return

    tabla = (
        df.groupby(field, dropna=False)
        .size()
        .reset_index(name="records")
        .sort_values("records", ascending=False)
    )

    total = tabla["records"].sum()
    if total > 0:
        tabla["percentage"] = (tabla["records"] / total * 100).round(4)
    else:
        tabla["percentage"] = 0.0

    tabla.to_csv(output_csv, index=False, encoding="utf-8-sig")


def asegurar_columnas(
    df: pd.DataFrame,
    columns: list[str],
    fill_value: object = pd.NA,
) -> pd.DataFrame:
    """Ensure required columns exist to avoid downstream groupby/sort errors."""
    for col in columns:
        if col not in df.columns:
            df[col] = fill_value

    return df


def construir_unidades_extraccion(
    gdf: gpd.GeoDataFrame,
    year_field: str,
    country_field: str,
    source_field: str,
    level1_field: str,
    level2_field: str,
) -> pd.DataFrame:
    """
    Build unique extraction units by lon, lat and year.

    One extraction unit represents a unique combination:
    longitude + latitude + reference year.
    """
    required_keys = ["_lon_join", "_lat_join", year_field]
    missing_keys = [field for field in required_keys if field not in gdf.columns]

    if missing_keys:
        raise ValueError(
            "No se pueden construir unidades de extracción. "
            f"Faltan campos clave: {missing_keys}"
        )

    optional_fields = [
        "xy_group_id",
        "tipo_grupo_xy",
        "n_registros",
        "n_paises",
        "n_fuentes",
        "n_anios",
        "n_nivel1",
        "n_nivel2",
        "anio_min",
        "anio_max",
        "pais_grupo",
        country_field,
        source_field,
        level1_field,
        level2_field,
    ]

    gdf = asegurar_columnas(
        gdf.copy(),
        [country_field, source_field, level1_field, level2_field],
    )

    grouped = gdf.groupby(required_keys, dropna=False)

    units = grouped.size().reset_index(name="n_records_extract_unit")

    existing_first_fields = [f for f in optional_fields if f in gdf.columns]

    if existing_first_fields:
        first_values = grouped[existing_first_fields].first().reset_index()
        units = units.merge(first_values, on=required_keys, how="left")

    for label, field in {
        "country": country_field,
        "source": source_field,
        "level1": level1_field,
        "level2": level2_field,
    }.items():
        if field in gdf.columns:
            nunique = (
                grouped[field]
                .nunique(dropna=True)
                .reset_index(name=f"n_unique_{label}_extract_unit")
            )
            units = units.merge(nunique, on=required_keys, how="left")

    sort_cols = [
        col
        for col in [year_field, country_field, "_lon_join", "_lat_join"]
        if col in units.columns
    ]

    if sort_cols:
        units = units.sort_values(sort_cols, na_position="last").reset_index(drop=True)
    else:
        units = units.reset_index(drop=True)

    units.insert(
        0,
        "extract_id",
        [f"S2SR_{i:09d}" for i in range(1, len(units) + 1)],
    )

    units = units.rename(
        columns={
            "_lon_join": "lon",
            "_lat_join": "lat",
            year_field: "year_ref",
            country_field: "country",
            source_field: "source",
            level1_field: "level_1",
            level2_field: "level_2",
        }
    )

    units = asegurar_columnas(
        units,
        ["country", "source", "level_1", "level_2", "year_ref"],
    )

    return units


def exportar_batches(
    units: pd.DataFrame,
    batch_size: int,
) -> pd.DataFrame:
    """
    Export CSV batches for GEE.

    The batch size is only the maximum number of extraction units per CSV.
    It does not change the data logic.
    """
    if batch_size <= 0:
        raise ValueError("batch_size debe ser mayor que 0.")

    BATCHES_DIR.mkdir(parents=True, exist_ok=True)

    for old_csv in BATCHES_DIR.glob("*.csv"):
        old_csv.unlink()

    if units.empty:
        batch_index = pd.DataFrame(
            columns=["batch_id", "country", "year_ref", "records", "batch_csv"]
        )
        batch_index.to_csv(
            TABLES_DIR / "s2_sr_gee_batch_index.csv",
            index=False,
            encoding="utf-8-sig",
        )
        return batch_index

    units = asegurar_columnas(units.copy(), ["country", "year_ref"])

    batch_records = []
    group_fields = ["country", "year_ref"]

    for (country, year_ref), df_group in units.groupby(group_fields, dropna=False):
        df_group = df_group.sort_values(["extract_id"]).reset_index(drop=True)

        n_batches = (len(df_group) + batch_size - 1) // batch_size

        for batch_idx in range(n_batches):
            start = batch_idx * batch_size
            end = min(start + batch_size, len(df_group))

            df_batch = df_group.iloc[start:end].copy()

            country_name = limpiar_nombre_archivo(country)
            year_name = limpiar_nombre_archivo(year_ref)

            batch_name = (
                f"s2sr_units_{country_name}_{year_name}_"
                f"batch_{batch_idx + 1:03d}"
            )
            batch_csv = BATCHES_DIR / f"{batch_name}.csv"

            df_batch["batch_id"] = batch_name
            df_batch.to_csv(batch_csv, index=False, encoding="utf-8-sig")

            batch_records.append(
                {
                    "batch_id": batch_name,
                    "country": country,
                    "year_ref": year_ref,
                    "records": len(df_batch),
                    "batch_csv": str(batch_csv),
                }
            )

    batch_index = pd.DataFrame(batch_records)
    batch_index.to_csv(
        TABLES_DIR / "s2_sr_gee_batch_index.csv",
        index=False,
        encoding="utf-8-sig",
    )

    return batch_index


def generar_reporte(
    total_input: int,
    total_eligible: int,
    total_units: int,
    total_batches: int,
    unmatched_xy: int,
    batch_size: int,
) -> None:
    """Generate a Markdown report for this module."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    contenido = "\n".join(
        [
            "# Preparación de insumos para GEE - Sentinel-2 SR",
            "",
            f"Fecha de ejecución: {fecha}",
            "",
            "## Propósito",
            "",
            (
                "Este módulo prepara la base de puntos evaluables para la "
                "caracterización espectro-temporal con Sentinel-2 Surface "
                "Reflectance en Google Earth Engine."
            ),
            "",
            "## Regla aplicada",
            "",
            "```text",
            f"{YEAR_MIN} <= Año <= {YEAR_MAX}",
            "```",
            "",
            (
                "No se seleccionan todavía muestras finales de entrenamiento, "
                "validación o prueba."
            ),
            "",
            "## Unidad de extracción para GEE",
            "",
            "La extracción en GEE se realizará una sola vez por combinación única:",
            "",
            "```text",
            "Longitud + Latitud + Año",
            "```",
            "",
            (
                "Los resultados espectrales podrán unirse posteriormente a todos "
                "los registros originales mediante `extract_id`."
            ),
            "",
            "## Resumen",
            "",
            "| Métrica | Valor |",
            "|---|---:|",
            f"| Total de registros de entrada | {total_input:,} |",
            f"| Registros elegibles {YEAR_MIN}-{YEAR_MAX} | {total_eligible:,} |",
            f"| Unidades únicas Longitud-Latitud-Año para GEE | {total_units:,} |",
            f"| Extracciones redundantes evitadas | {total_eligible - total_units:,} |",
            f"| Registros sin unión con grupos_xy | {unmatched_xy:,} |",
            f"| Tamaño máximo de batch | {batch_size:,} |",
            f"| Total de batches generados | {total_batches:,} |",
            "",
            "## Salidas principales",
            "",
            f"- GeoPackage de registros elegibles: `{OUTPUT_GPKG}`",
            f"- Capa: `{OUTPUT_LAYER}`",
            f"- CSV de unidades de extracción: `{EXTRACT_UNITS_CSV}`",
            f"- Carpeta de batches para GEE: `{BATCHES_DIR}`",
            f"- Tablas resumen: `{TABLES_DIR}`",
            "",
        ]
    )

    report_path = REPORTS_DIR / "06_s2_sr_gee_input.md"
    report_path.write_text(contenido, encoding="utf-8")


def validar_config(config: dict[str, Any]) -> tuple[Path, str, dict[str, str]]:
    """Validate config and return input file, layer name and field mapping."""
    input_data = config.get("input_data", {})
    fields_cfg = config.get("fields", {})

    if not isinstance(input_data, dict):
        raise ValueError("La sección input_data de config/config.yaml no es válida.")

    if not isinstance(fields_cfg, dict):
        raise ValueError("La sección fields de config/config.yaml no es válida.")

    gpkg_rel = input_data.get("gpkg_file")
    table_name = input_data.get("gpkg_layer")

    if not gpkg_rel:
        raise ValueError("No se definió input_data.gpkg_file en config/config.yaml.")

    if not table_name:
        raise ValueError("No se definió input_data.gpkg_layer en config/config.yaml.")

    gpkg_path = resolver_ruta_proyecto(gpkg_rel)

    if not gpkg_path.exists():
        raise FileNotFoundError(
            "No existe el GeoPackage configurado en input_data.gpkg_file: "
            f"{gpkg_path}"
        )

    field_map = {
        "longitude": str(fields_cfg.get("longitude", "Longitud")),
        "latitude": str(fields_cfg.get("latitude", "Latitud")),
        "country": str(fields_cfg.get("country", "Pais_es")),
        "source": str(fields_cfg.get("source", "Fuente")),
        "year": str(fields_cfg.get("year", "Año")),
        "level_1": str(fields_cfg.get("level_1", "Nivel_1")),
        "level_2": str(fields_cfg.get("level_2", "Nivel_2")),
    }

    return gpkg_path, str(table_name), field_map


def validar_campos_requeridos(
    gdf: gpd.GeoDataFrame,
    required_fields: list[str],
) -> None:
    """Validate fields required in the input GeoPackage."""
    missing = [field for field in required_fields if field not in gdf.columns]

    if missing:
        available = sorted([str(col) for col in gdf.columns])
        raise ValueError(
            "Faltan campos requeridos en el GeoPackage original: "
            f"{missing}\n\nCampos disponibles:\n{available}"
        )


def preparar_gdf_elegible(
    gdf: gpd.GeoDataFrame,
    grupos_xy: pd.DataFrame,
    field_map: dict[str, str],
) -> tuple[gpd.GeoDataFrame, int]:
    """Filter records by year and join XY group information."""
    lon_field = field_map["longitude"]
    lat_field = field_map["latitude"]
    year_field = field_map["year"]

    validar_campos_requeridos(gdf, [lon_field, lat_field, year_field])

    gdf = gdf.copy()
    gdf[year_field] = pd.to_numeric(gdf[year_field], errors="coerce")

    gdf_eligible = gdf[
        (gdf[year_field] >= YEAR_MIN)
        & (gdf[year_field] <= YEAR_MAX)
    ].copy()

    gdf_eligible["_lon_join"] = normalizar_coord(gdf_eligible[lon_field])
    gdf_eligible["_lat_join"] = normalizar_coord(gdf_eligible[lat_field])

    # Avoid merge suffixes when rerunning over data that already has these columns.
    overlap_cols = [
        col
        for col in grupos_xy.columns
        if col in gdf_eligible.columns and col not in ["_lon_join", "_lat_join"]
    ]

    if overlap_cols:
        gdf_eligible = gdf_eligible.drop(columns=overlap_cols)

    gdf_eligible = gdf_eligible.merge(
        grupos_xy,
        on=["_lon_join", "_lat_join"],
        how="left",
    )

    unmatched_xy = int(gdf_eligible["xy_group_id"].isna().sum())

    return gdf_eligible, unmatched_xy


def exportar_resumenes(
    gdf_eligible: gpd.GeoDataFrame,
    units: pd.DataFrame,
    batch_index: pd.DataFrame,
    total_input: int,
    unmatched_xy: int,
    batch_size: int,
    field_map: dict[str, str],
) -> None:
    """Export summary CSV tables."""
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    year_field = field_map["year"]
    country_field = field_map["country"]
    source_field = field_map["source"]
    level1_field = field_map["level_1"]
    level2_field = field_map["level_2"]

    summary = pd.DataFrame(
        [
            {
                "year_min": YEAR_MIN,
                "year_max": YEAR_MAX,
                "total_input_records": total_input,
                "eligible_records": len(gdf_eligible),
                "extract_units_lon_lat_year": len(units),
                "redundant_extractions_avoided": len(gdf_eligible) - len(units),
                "unmatched_xy_records": unmatched_xy,
                "batch_size": batch_size,
                "n_batches": len(batch_index),
                "output_gpkg": str(OUTPUT_GPKG),
                "output_layer": OUTPUT_LAYER,
                "extract_units_csv": str(EXTRACT_UNITS_CSV),
                "batches_dir": str(BATCHES_DIR),
            }
        ]
    )

    summary.to_csv(
        TABLES_DIR / "s2_sr_eligible_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    exportar_tabla_conteo(
        gdf_eligible,
        country_field,
        TABLES_DIR / "s2_sr_eligible_by_country.csv",
    )
    exportar_tabla_conteo(
        gdf_eligible,
        year_field,
        TABLES_DIR / "s2_sr_eligible_by_year.csv",
    )
    exportar_tabla_conteo(
        gdf_eligible,
        source_field,
        TABLES_DIR / "s2_sr_eligible_by_source.csv",
    )
    exportar_tabla_conteo(
        gdf_eligible,
        level1_field,
        TABLES_DIR / "s2_sr_eligible_by_level1.csv",
    )
    exportar_tabla_conteo(
        gdf_eligible,
        level2_field,
        TABLES_DIR / "s2_sr_eligible_by_level2.csv",
    )
    exportar_tabla_conteo(
        gdf_eligible,
        "tipo_grupo_xy",
        TABLES_DIR / "s2_sr_eligible_by_tipo_grupo_xy.csv",
    )

    units = asegurar_columnas(units.copy(), ["country", "year_ref"])

    units_by_country_year = (
        units.groupby(["country", "year_ref"], dropna=False)
        .size()
        .reset_index(name="extract_units")
        .sort_values(["country", "year_ref"], na_position="last")
    )

    units_by_country_year.to_csv(
        TABLES_DIR / "s2_sr_extract_units_by_country_year.csv",
        index=False,
        encoding="utf-8-sig",
    )


def exportar_gpkg(gdf_eligible: gpd.GeoDataFrame) -> None:
    """Export eligible records to GeoPackage."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    drop_cols = [col for col in ["_lon_join", "_lat_join"] if col in gdf_eligible.columns]
    export_gdf = gdf_eligible.drop(columns=drop_cols)

    if OUTPUT_GPKG.exists():
        OUTPUT_GPKG.unlink()

    export_gdf.to_file(
        OUTPUT_GPKG,
        layer=OUTPUT_LAYER,
        driver="GPKG",
    )


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Prepara puntos 2018-2022 para extracción Sentinel-2 SR en GEE."
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=(
            "Número máximo de unidades Longitud-Latitud-Año por CSV batch. "
            f"Valor por defecto: {DEFAULT_BATCH_SIZE}."
        ),
    )

    parser.add_argument(
        "--skip-gpkg",
        action="store_true",
        help="No exporta el GeoPackage completo de registros elegibles.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    crear_carpetas_salida()

    if args.batch_size <= 0:
        raise ValueError("--batch-size debe ser mayor que 0.")

    config = cargar_yaml(CONFIG_PATH)
    gpkg_path, table_name, field_map = validar_config(config)

    lon_field = field_map["longitude"]
    lat_field = field_map["latitude"]
    year_field = field_map["year"]
    country_field = field_map["country"]
    source_field = field_map["source"]
    level1_field = field_map["level_1"]
    level2_field = field_map["level_2"]

    print("============================================================")
    print("PGBM - Preparación de puntos para GEE Sentinel-2 SR")
    print("============================================================")
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Config: {CONFIG_PATH}")
    print(f"Base intermedia: {INTERIM_DB_PATH}")
    print(f"GeoPackage: {gpkg_path}")
    print(f"Capa: {table_name}")
    print(f"Periodo: {YEAR_MIN}-{YEAR_MAX}")
    print(f"Campo año: {year_field}")
    print(f"Campo longitud: {lon_field}")
    print(f"Campo latitud: {lat_field}")
    print(f"Campo país: {country_field}")
    print(f"Campo fuente: {source_field}")
    print(f"Campo nivel 1: {level1_field}")
    print(f"Campo nivel 2: {level2_field}")
    print(f"Batch size: {args.batch_size:,}")

    registrar_log("Inicio de preparación de puntos para GEE Sentinel-2 SR.")

    print("\nCargando grupos_xy del Módulo 3B...")
    grupos_xy = cargar_grupos_xy()
    print(f"Grupos XY cargados: {len(grupos_xy):,}")

    print("\nLeyendo GeoPackage original...")
    gdf = gpd.read_file(gpkg_path, layer=table_name)
    total_input = len(gdf)
    print(f"Total registros entrada: {total_input:,}")

    print(f"\nFiltrando registros elegibles {YEAR_MIN}-{YEAR_MAX}...")
    gdf_eligible, unmatched_xy = preparar_gdf_elegible(
        gdf=gdf,
        grupos_xy=grupos_xy,
        field_map=field_map,
    )

    print(f"Registros elegibles {YEAR_MIN}-{YEAR_MAX}: {len(gdf_eligible):,}")
    print(f"Registros elegibles sin unión con grupos_xy: {unmatched_xy:,}")

    print("\nConstruyendo unidades únicas Longitud-Latitud-Año para GEE...")
    units = construir_unidades_extraccion(
        gdf=gdf_eligible,
        year_field=year_field,
        country_field=country_field,
        source_field=source_field,
        level1_field=level1_field,
        level2_field=level2_field,
    )

    print(f"Unidades de extracción GEE: {len(units):,}")

    units.to_csv(EXTRACT_UNITS_CSV, index=False, encoding="utf-8-sig")
    print(f"CSV unidades GEE: {EXTRACT_UNITS_CSV}")

    extract_lookup = units[
        ["extract_id", "lon", "lat", "year_ref", "n_records_extract_unit"]
    ].rename(
        columns={
            "lon": "_lon_join",
            "lat": "_lat_join",
            "year_ref": year_field,
        }
    )

    overlap_cols = [
        col
        for col in ["extract_id", "n_records_extract_unit"]
        if col in gdf_eligible.columns
    ]

    if overlap_cols:
        gdf_eligible = gdf_eligible.drop(columns=overlap_cols)

    gdf_eligible = gdf_eligible.merge(
        extract_lookup,
        on=["_lon_join", "_lat_join", year_field],
        how="left",
    )

    missing_extract_id = int(gdf_eligible["extract_id"].isna().sum())
    if missing_extract_id:
        print(
            "Advertencia: algunos registros elegibles no recibieron extract_id: "
            f"{missing_extract_id:,}"
        )

    print("\nExportando batches CSV para GEE...")
    batch_index = exportar_batches(units, batch_size=args.batch_size)
    print(f"Batches generados: {len(batch_index):,}")

    print("\nExportando tablas resumen...")
    exportar_resumenes(
        gdf_eligible=gdf_eligible,
        units=units,
        batch_index=batch_index,
        total_input=total_input,
        unmatched_xy=unmatched_xy,
        batch_size=args.batch_size,
        field_map=field_map,
    )

    if not args.skip_gpkg:
        print("\nExportando GeoPackage de registros elegibles...")
        exportar_gpkg(gdf_eligible)
        print(f"GeoPackage exportado: {OUTPUT_GPKG}")
    else:
        print("\nSe omitió la exportación del GeoPackage por --skip-gpkg.")

    print("\nGenerando reporte...")
    generar_reporte(
        total_input=total_input,
        total_eligible=len(gdf_eligible),
        total_units=len(units),
        total_batches=len(batch_index),
        unmatched_xy=unmatched_xy,
        batch_size=args.batch_size,
    )

    registrar_log(
        "Preparación de puntos para GEE Sentinel-2 SR ejecutada correctamente. "
        f"Registros elegibles: {len(gdf_eligible)}. "
        f"Unidades GEE: {len(units)}. "
        f"Batches: {len(batch_index)}."
    )

    print("\nDone.")
    print(f"Registros elegibles {YEAR_MIN}-{YEAR_MAX}: {len(gdf_eligible):,}")
    print(f"Unidades únicas Longitud-Latitud-Año: {len(units):,}")
    print(f"Extracciones redundantes evitadas: {len(gdf_eligible) - len(units):,}")
    print(f"Batches generados: {len(batch_index):,}")
    print(f"CSV unidades GEE: {EXTRACT_UNITS_CSV}")
    print(f"GeoPackage: {OUTPUT_GPKG}")
    print(f"Reporte: {REPORTS_DIR / '06_s2_sr_gee_input.md'}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        registrar_log(
            "Error durante la preparación de puntos para GEE Sentinel-2 SR. "
            f"{type(exc).__name__}: {exc}"
        )
        traceback.print_exc()
        raise
